### ISSUE TITLE
pytsk install error

### ISSUE THREAD

**Issue by laissezfarrell** [BitCurator/bitcurator-distro-salt#11]
Running the distro install script, most packages installed successfully, with the exception of pytsk, which resulted in error. 

It appears that the wget command was looking for https://github.com/py4n6/pytsk/releases/download/20160721/pytsk3-20160721.tar.gz which doesn't seem to exist any longer (the repo has releases dating to 2019 but nothing earlier https://github.com/py4n6/pytsk/releases/)

Here's the relevant part of the bitcurator-install.log file:

`Got pytsk3 with wget
tar (child): pytsk3-20160721.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
python3: can't open file 'setup.py': [Errno 2] No such file or directory
python3: can't open file 'setup.py': [Errno 2] No such file or directory`

And the stdout from install.sh:
` 

      Result: False
     Comment: Command "cd /tmp
              wget -q https://github.com/py4n6/pytsk/releases/download/20160721/pytsk3-20160721.tar.gz
              echo "Got pytsk3 with wget" >> /var/log/bitcurator-install.log 2>&1
              tar -zxf pytsk3-20160721.tar.gz >> /var/log/bitcurator-install.log 2>&1
              cd pytsk3-20160721
              python3 setup.py build >> /var/log/bitcurator-install.log 2>&1
              python3 setup.py install >> /var/log/bitcurator-install.log 2>&1
              cd /tmp
              rm -rf pytsk3-20160721
              rm pytsk3-20160721.tar.gz
              " run
     Started: 10:16:32.453678
    Duration: 268.769 ms
     Changes:   
              ----------
              pid:
                  117408
              retcode:
                  1
              stderr:
                  /bin/bash: line 4: cd: pytsk3-20160721: No such file or directory
                  rm: cannot remove 'pytsk3-20160721.tar.gz': No such file or directory
              stdout:`

**Comment by kamwoods** [comment]
Seems pytsk has undergone a lot of updates, and the maintainer has wiped the old versions from GitHub. Removed the source-specific install, now installing from PyPI (https://pypi.org/project/pytsk3/). Also updated tsk release used to 4.10.2.

Tagged and released as Bitcurator 2.2.12.

**Comment by laissezfarrell** [comment]
Thanks!
